exclude: ".git"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff-format # formatter
        types_or: [python, pyi, jupyter, toml]
      - id: ruff # linter
        types_or: [python, pyi, jupyter, toml]
        args: [--fix]



  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=13000']  # Example to increase limit to 1 GB
