# config.yaml

rand_config:
  table:
    thickness: 0.05  # in meters
    width: 2.0    # in meters
    length: 4.0   # in meters
    leg_length: 0.5
    leg_thickness: 0.05

  robot:
    init_pose:
      x: 0.0
      y: 0.0
      z: 0.0
    pos_range:
      x_min: -0
      x_max: 0
      y_min: -0
      y_max: 0
    init_rotation: [0, 0, 0]

  simulation:
    gravity: 9.81  # m/s^2
    timestep: 0.01  # seconds
    max_steps: 1000
  
  camera:
    rad_range: 1.57
  
  lighting:
    ambient_min: 0.5
    ambient_max: 1.
  
  object:
    pos_scale: 0.2
    pos_offset: 0.1

  goal:
    offset_to_object_min: -0.2
    offset_to_object_max: 0.2
