defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_diffusion_agent.TrainDiffusionAgent # Train
# _target_: agent.eval.eval_diffusion_img_agent_real.EvalImgDiffusionAgentReal # Eval
# _target_: agent.val.val_diffusion_img_agent_real.ValImgDiffusionAgentReal # Val

job_id: 0
name: ${env}_diffusion_unet_vit_ta${horizon_steps}_td${denoising_steps}
# logdir: ${oc.env:GDC_LOG_DIR}/real_pick_and_place/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
logdir: ${oc.env:GDC_LOG_DIR}/real_pick_and_place/${job_id}_vit
train_dataset_path: ${oc.env:GDC_DATA_DIR}/traj_data/dataset_jsg_jsg_2cam_96.npz

# Eval
# base_policy_path: /home/lab/droid/ckpts/state_3350_resnet_aug_groupnorm_js.pt
# normalization_stats_path: /home/lab/droid/traj_data/norm_no_vel.npz
base_policy_path: null
normalization_stats_path: null

seed: 42
device: cuda
env: pick_and_place
obs_dim: 8  # 7+7+1  6+1
action_dim: 8
denoising_steps: 100
horizon_steps: 8
cond_steps: 2
img_cond_steps: 1
gpu_id: null
debug: False

# Eval
act_steps: 8
use_ddim: true
ddim_steps: 10
ordered_obs_keys: ['joint_positions', 'gripper_position']
n_steps: 300

# Val
batch_size: 1
render_num: 0

wandb:
  entity: ${oc.env:GDC_WANDB_ENTITY}
  project: realworld-${env}-pretrain
  run: ${job_id}_${name}

shape_meta:
  obs:
    rgb:
      shape: [3, 96, 96]  # not counting img_cond_steps
    state:
      shape: ${[obs_dim]}
  action: 
    shape: ${[action_dim]}

train:
  n_epochs: 8000
  learning_rate: 1e-4
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: ${train.n_epochs}
    warmup_steps: 100
    min_lr: 1e-5
  epoch_start_ema: 20
  update_ema_freq: 5
  save_model_freq: 50
  # validation
  train_split: 0.9
  val_batch_size: ${train.batch_size}
  val_freq: 50
  # dataloader
  store_gpu: False
  num_workers: 1
  persistent_workers: True
  batch_size: 32

model:
  _target_: model.diffusion.diffusion.DiffusionModel
  device: ${device}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  predict_epsilon: True
  denoised_clip_value: 1.0

  # Eval
  use_ddim: ${use_ddim}
  ddim_steps: ${ddim_steps}
  network_path: ${base_policy_path}
  
  # network_path: /home/irom-lab/projects/guided-data-collection/guided_dc/diffusion/state_2500_vel.pt
  network:
    _target_: model.diffusion.unet.VisionUnet1D
    diffusion_step_embed_dim: 128
    dim: 256
    dim_mults: [1, 2, 4]
    kernel_size: 5
    n_groups: 8
    cond_predict_scale: True
    smaller_encoder: False
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    action_dim: ${action_dim}
    augment: false
    dropout: 0
    
    # visual_feature_dim: ${model.network.spatial_emb}

    spatial_emb: 0
    use_compress: False
    backbone:
      _target_: model.common.vit.VitEncoder
      obs_shape: ${shape_meta.obs.rgb.shape}
      img_h: ${shape_meta.obs.rgb.shape[1]}
      img_w: ${shape_meta.obs.rgb.shape[2]}
      img_cond_steps: ${img_cond_steps}
      num_channel: ${shape_meta.obs.rgb.shape[0]}
      cfg:
        patch_size: 8 # TODO
        depth: 2
        embed_dim: 512
        num_heads: 8
        embed_style: embed2
        embed_norm: 0
        share_embed_head: False
        num_views: 2
        feature_aggregation: cls


ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  use_img: True
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  max_n_episodes: 100
  cond_steps: ${cond_steps}
  img_cond_steps: ${img_cond_steps}
  device: ${device}
  use_delta_actions: false
  store_gpu: ${train.store_gpu}
  