defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_diffusion_agent.TrainDiffusionAgent # Train
# _target_: agent.eval.eval_diffusion_img_agent_real.EvalImgDiffusionAgentReal # Eval
# _target_: agent.val.val_diffusion_img_agent_real.ValImgDiffusionAgentReal # Val

job_id: 0
gpu_id: null
name: dinov2_${dataset_name}_${env}
# logdir: ${oc.env:GDC_LOG_DIR}/real_pick_and_place/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
logdir: ${oc.env:GDC_LOG_DIR}/real_pick_and_place/${job_id}_dinov2
dataset_name: eefg_eefg_2cam_96
train_dataset_path: ${oc.env:GDC_DATA_DIR}/traj_data/dataset_${dataset_name}.npz

wandb:
  entity: ${oc.env:GDC_WANDB_ENTITY}
  project: realworld-${env}
  run: ${job_id}_${name}

# Eval
# base_policy_path: /home/lab/droid/ckpts/state_3350_resnet_aug_groupnorm_js.pt
# normalization_stats_path: /home/lab/droid/traj_data/norm_no_vel.npz
base_policy_path: null
normalization_stats_path: null

seed: 42
device: cuda
env: pick_and_place
obs_dim: 7  # 7+7+1  6+1
action_dim: 7
denoising_steps: 100
horizon_steps: 16
cond_steps: 2
img_cond_steps: 2
debug: False

# Eval
act_steps: 8
use_ddim: true
ddim_steps: 10
ordered_obs_keys: ['joint_positions', 'gripper_position']
n_steps: 300

shape_meta:
  obs:
    rgb:
      shape: [3, 96, 96]  # not counting img_cond_steps
    state:
      shape: ${[obs_dim]}
  action: 
    shape: ${[action_dim]}

train:
  n_epochs: 8000
  learning_rate: 1e-4
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: ${train.n_epochs}
    warmup_steps: 100
    min_lr: 1e-5
  epoch_start_ema: 20
  update_ema_freq: 5
  save_model_freq: 50
  # dataloader
  store_gpu: False
  num_workers: 1
  persistent_workers: True
  batch_size: 128
  # validation
  train_split: 0.85
  val_batch_size: ${train.batch_size}
  val_freq: 50

model:
  _target_: model.diffusion.diffusion.DiffusionModel
  device: ${device}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  predict_epsilon: True
  denoised_clip_value: 1.0

  # Eval
  use_ddim: ${use_ddim}
  ddim_steps: ${ddim_steps}
  network_path: ${base_policy_path}
  
  network:
    _target_: model.diffusion.unet.VisionUnet1D
    diffusion_step_embed_dim: 128
    dim: 256
    dim_mults: [1, 2, 4]
    kernel_size: 5
    n_groups: 8
    cond_predict_scale: True
    smaller_encoder: False
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    action_dim: ${action_dim}
    
    use_compress: False
    dropout: 0
    spatial_emb: 0
    augment: false
    backbone:
      _target_: model.common.dinov2.DINOv2Encoder
      model_name: 'vit_base_patch14_dinov2.lvd142m'
      pretrained: false
      frozen: false
      use_lora: false
      lora_rank: 8
      drop_path_rate: 0.0
      img_size: ${shape_meta.obs.rgb.shape[1]}
      share_rgb_model: False
      num_views: 2
      img_cond_steps: ${img_cond_steps}

      # feature_aggregation: # 'none', 'mean', 'concat', 'spatial_emb', 'compress'
      #   type: 'spatial_emb'
      #   spatial_emb: 128
      #   cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
      #   dropout: 0

      #   type: 'compress'
      #   visual_feature_dim: 128
      #   dropout: 0
        

      # aug:
      #   _target_: model.common.modules.CropRandomizer
      #   input_shape: ${shape_meta.obs.rgb.shape}
      #   crop_height_pct: 0.9
      #   crop_width_pct: 0.9
      #   num_crops: 1
      #   pos_enc: false 

ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  use_img: True
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  max_n_episodes: 100
  cond_steps: ${cond_steps}
  img_cond_steps: ${img_cond_steps}
  device: ${device}
  use_delta_actions: false
  store_gpu: ${train.store_gpu}
  